.\"-
.\"Released as "All Rights Reserved"
.\"until further notice/application of a formal license
.\"
.Dd August 6, 2014
.Dt pwd 1
.Os Anima
.Sh NAME
.Nm pwd
.Nd return working directory name.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility writes the absolute pathname of the current working directory to the standard output.
The
.Pp
Some shells may provide a builtin pwd command which is similar or identical to this utility.  Consult the 
.Ar builtin(1) 
manual page.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr builtin 1 ,
.Xr cd 1 ,
.Xr csh 1 ,
.Xr sh 1 ,
.Xr getcwd 3
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2001
specification.
.Sh BUGS
In 
.Ar csh (1) 
the command 
.Ar dirs 
is always faster because it is built into that shell.  
.Pp
However, it can give a different answer in the rare case that the current directory or a containing directory was moved after the shell 
descended into it.