.\"-
.\"Released as "All Rights Reserved"
.\"until further notice/application of a formal license
.\"
.Dd June 10, 2014
.Dt uname 1
.Os Anima
.Sh NAME
.Nm uname
.Nd print operating system name
.Sh SYNOPSIS
.Nm
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility writes symbols representing one or more system characteristics to the standard output.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr machine 1 ,
.Xr sw_vers 1 ,
.Xr uname 3 
.Sh STANDARDS
The
.Nm
utility conforms to IEEE Std 1003.2-1992 (``POSIX.2'').