.\"-
.\"Released as "All Rights Reserved"
.\"until further notice/application of a formal license
.\"
.Dd July 3, 2014
.Dt yes 1
.Os Anima
.Sh NAME
.Nm yes
.Nd be repetitively affirmative
.Sh SYNOPSIS
.Nm
.Op expletitive
.Sh DESCRIPTION
The
.Nm
utility outputs expletive or, by default, "y", forever.
.Sh EXIT STATUS
.Ex -std
.Sh HISTORY
A
.Nm
utility first appeared in BSD 4.0.